export const root: string;
export const featureOne: string;
export const featureTwo: string;
export const featureThree: string;
export const featureRow: string;
export const featureCardRight: string;
export const featureCardLeft: string;
export const featurePoints: string;
export const featureTitle: string;
