export const menu: string;
export const menuList: string;
export const menuItem: string;
export const menuLink: string;
export const main: string;
export const selected: string;
export const dropdown: string;
export const side: string;
export const sub: string;
