export const root: string;
export const link: string;
export const inverse: string;
export const selected: string;
export const dropdownLink: string;
export const dropdownIcon: string;
export const children: string;
export const expanded: string;
export const collapsed: string;
